version: '2'
services:
    myapp-postgresql:
        image: postgres:9.6.5
        # volumes:
        #     - ~/volumes/jhipster/myApp/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=myApp
            - POSTGRES_PASSWORD=
        #command: --"myapp.org_id"="-1"
        ports:
            - 5432:5432
        volumes:
            - ./init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
